FROM ruby:3.3.6

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /app

COPY backend/Gemfile backend/Gemfile.lock ./
RUN bundle install

COPY backend/ .

COPY backend/entrypoint.sh /usr/bin/entrypoint.sh
ENTRYPOINT ["sh", "/usr/bin/entrypoint.sh"]


EXPOSE 3000


CMD ["rails", "server", "-b", "0.0.0.0"]
