version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data:
