version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
